name: Atualizar BaseMunicipioMensal.csv

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependências
        run: pip install requests beautifulsoup4 pandas gspread google-auth

      - name: Rodar script de download
        run: python scripts/iso_bot3.py
        env:
          GCP_SHEETS_CREDENTIALS: ${{ secrets.GCP_SHEETS_CREDENTIALS }}

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add data/BaseMunicipioMensal.csv logs/isp_bot.log
          git commit -m "Atualização automática do CSV" || echo "Sem mudanças"
          git push
